/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RecommendedImport } from './routes/recommended'
import { Route as PopularImport } from './routes/popular'
import { Route as ExploreImport } from './routes/explore'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const RecommendedRoute = RecommendedImport.update({
  id: '/recommended',
  path: '/recommended',
  getParentRoute: () => rootRoute,
} as any)

const PopularRoute = PopularImport.update({
  id: '/popular',
  path: '/popular',
  getParentRoute: () => rootRoute,
} as any)

const ExploreRoute = ExploreImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreImport
      parentRoute: typeof rootRoute
    }
    '/popular': {
      id: '/popular'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof PopularImport
      parentRoute: typeof rootRoute
    }
    '/recommended': {
      id: '/recommended'
      path: '/recommended'
      fullPath: '/recommended'
      preLoaderRoute: typeof RecommendedImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/popular': typeof PopularRoute
  '/recommended': typeof RecommendedRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/popular': typeof PopularRoute
  '/recommended': typeof RecommendedRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/popular': typeof PopularRoute
  '/recommended': typeof RecommendedRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explore' | '/popular' | '/recommended'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explore' | '/popular' | '/recommended'
  id: '__root__' | '/' | '/explore' | '/popular' | '/recommended'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  PopularRoute: typeof PopularRoute
  RecommendedRoute: typeof RecommendedRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  PopularRoute: PopularRoute,
  RecommendedRoute: RecommendedRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/explore",
        "/popular",
        "/recommended"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/explore": {
      "filePath": "explore.tsx"
    },
    "/popular": {
      "filePath": "popular.tsx"
    },
    "/recommended": {
      "filePath": "recommended.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
